apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
    
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: zergi0/hello-world:latest
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hello-world-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001